title: Super Turner Bros
description: Super Turner Bros Content
sitename: SuperTurnerBros
baseurl:
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
